name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Inject API key and deploy
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "window.API_KEY = '${API_KEY}';" > ./apiKey.js
          npm run deploy
